//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zayavki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка.
    /// </summary>
    // *** Start programmer edit section *** (Заявка CustomAttributes)

    // *** End programmer edit section *** (Заявка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаE", new string[] {
            "Дата as \'Дата\'",
            "Клиент as \'Клиент\'",
            "Клиент.Имя as \'Имя\'"}, Hidden=new string[] {
            "Клиент.Имя"})]
    [AssociatedDetailViewAttribute("ЗаявкаE", "Услуга", "УслугаE", true, "", "Услуга", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаявкаE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ЗаявкаL", new string[] {
            "Дата as \'Дата\'",
            "Клиент.Имя as \'Клиент\'"})]
    public class Заявка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Zayavki.Клиент fКлиент;
        
        private IIS.Zayavki.DetailArrayOfУслуга fУслуга;
        
        // *** Start programmer edit section *** (Заявка CustomMembers)

        // *** End programmer edit section *** (Заявка CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Дата CustomAttributes)

        // *** End programmer edit section *** (Заявка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Дата Get start)

                // *** End programmer edit section *** (Заявка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заявка.Дата Get end)

                // *** End programmer edit section *** (Заявка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Дата Set start)

                // *** End programmer edit section *** (Заявка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заявка.Дата Set end)

                // *** End programmer edit section *** (Заявка.Дата Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заявка.Клиент CustomAttributes)
        [NotNull()]
        public virtual IIS.Zayavki.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Клиент Get start)

                // *** End programmer edit section *** (Заявка.Клиент Get start)
                IIS.Zayavki.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заявка.Клиент Get end)

                // *** End programmer edit section *** (Заявка.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Клиент Set start)

                // *** End programmer edit section *** (Заявка.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заявка.Клиент Set end)

                // *** End programmer edit section *** (Заявка.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Услуга CustomAttributes)

        // *** End programmer edit section *** (Заявка.Услуга CustomAttributes)
        public virtual IIS.Zayavki.DetailArrayOfУслуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Услуга Get start)

                // *** End programmer edit section *** (Заявка.Услуга Get start)
                if ((this.fУслуга == null))
                {
                    this.fУслуга = new IIS.Zayavki.DetailArrayOfУслуга(this);
                }
                IIS.Zayavki.DetailArrayOfУслуга result = this.fУслуга;
                // *** Start programmer edit section *** (Заявка.Услуга Get end)

                // *** End programmer edit section *** (Заявка.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Услуга Set start)

                // *** End programmer edit section *** (Заявка.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (Заявка.Услуга Set end)

                // *** End programmer edit section *** (Заявка.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаE", typeof(IIS.Zayavki.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаL", typeof(IIS.Zayavki.Заявка));
                }
            }
        }
    }
}
